### ISSUE TITLE
about novel files？

### ISSUE THREAD

**Issue by dmuqlzhang** [ucbdrive/few-shot-object-detection#13]
![image](https://user-images.githubusercontent.com/47552281/79201494-bbc36780-7e6a-11ea-9b1e-7d481962c407.png)
faster_rcnn_R_101_FPN_ft_novel1_1shot.yaml file is not exist？ can you share it？
![image](https://user-images.githubusercontent.com/47552281/79201365-8ae33280-7e6a-11ea-9ad0-2ecdf8de619c.png)

**Comment by thomasehuang** [comment]
Hello,

We do not actually do this step for PASCAL VOC, so that's why the config files are not provided. Instead, we just randomly initialize the novel weights. I will copy and paste the config file you highlighted anyways in case you still want to try it out. You can also look at the COCO and LVIS config files to see how they are used.

```
_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base1/model_reset_remove.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_novel1_1shot", )
  TEST: ('voc_2007_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (500, )
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel1_1shot"
```

Hope that helps! Let me know if you run into any issues with this.
