### ISSUE TITLE
fine-tune result is great but demo can't detected anything

### ISSUE THREAD

**Issue by AISoltani** [ucbdrive/few-shot-object-detection#135]
Hi
I used a custom dataset on this project, which has great result in the fine tune step( eval result was great ) , but when I try to use the demo to detect the image, it does not detect anything, what is my problem?....base model, combine model and novel model can detect but final model from fine tune step can't!!!...(my dataset type was like pascal voc, jpg with xml).

i tested with both way like base train >> random initial >> fine tune and also base train >> random initial>>  novel train >> combine and fine tune...all of them have good result in terminal but final model can't detected anything with demo ...this is my final result from fine tune stage:

![result](https://user-images.githubusercontent.com/56760080/136528351-1a172cc9-f041-4931-bb2d-0b9c7ee48a68.PNG)

thanks for help.

**Comment by thomasehuang** [comment]
What command are you running when using the demo? Seems like an issue on the demo side rather than the model.

**Comment by AISoltani** [comment]
> What command are you running when using the demo? Seems like an issue on the demo side rather than the model.

First thanks for your answer, I tried all week and could not solve the problem and pls support us until the complete solution pls....
well ...i used this command:

`python3 -m demo.demo --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_ft_all1_1shot.yaml --input image1.jpg --opts MODEL.WEIGHTS checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_ft_normalized_all1_1shot_randnovel/model_final.pth`

this model_final was generated from fine tuning stage and my config is `faster_rcnn_R_101_FPN_ft_all1_1shot.yaml` and inside the config:
```
_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_all2/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 32
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_all1_1shot',)
  TEST: ('voc_2007_test_all1',)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (3000,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_ft_normalized_all1_1shot_randnovel"
```
i have 32 class if i use novel train i need to choose my combine model for weights in fine tuning and if i use random intial i choose model surgery for weights but at all demo can not detected after fine tuning.
I will rewrite the way I do my work in detail from the beginning. Maybe you can better guide me.
first my dataset is like pascal voc, jpg for images and xml for labels.
i use this command for base training :

`CUDA_VISIBLE_DEVICES=0 python3 -m tools.train_net --config-file configs/PascalVOC-detection/split1/faster_rcnn_R_101_FPN_base1.yaml`

and inside the base config is:
```
_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/cudaa/Downloads/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 24
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base1',)
  TEST: ('voc_2007_test_base1',)
SOLVER:
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
OUTPUT_DIR: "checkpoints/voc/faster_rcnn/faster_rcnn_R_101_FPN_base-final"
```

and because i have 32 class , 24 class for base and 8 class for novel...
after random initialize step i use this config `faster_rcnn_R_101_FPN_ft_all1_1shot.yaml` for fine tuning on surgery model (or use this command with 10shot) as i said above, and use this also for demo. Why my result in terminal was good but my model after fine tuning stage could not detected anything with demo?!
